Improve CSV loader error handling
facontidavide/PlotJuggler pull request #721
Opened 2022-08-09 23:33 UTC by Bartimaeus-

**Summary**
- Allow PlotJuggler to load CSV files with non-monotonic data with a warning (data is sorted to be monotonic) instead of aborting
- Improvements to error handling dialogs with additional information 

**Handling Non-Monotonic data**
The csv loader would reject csv files that didn't have the data sorted strictly monotonically and would abort loading the file if this was detected. This isn't necessary as the push_back() function used to add the data in the TimeseriesBase class already detects this and inserts new values into the correct place. Since non-monotonic time might be unexpected by the user this change brings up a dialog window where the user can choose to abort or continue with extra information that can be viewed:

![image](https://user-images.githubusercontent.com/2954254/183778639-069921bc-c21e-4523-b06e-668abf8224cb.png)

**Other Improvements**
These are mostly quality of life improvements. I got tired of having to switch between PlotJuggler and my csv file trying to figure out where the issue was.
Examples of the other dialog windows:
![image](https://user-images.githubusercontent.com/2954254/183778698-a12a9484-de50-411c-99f7-58abf570b35d.png)

Failed to parse timestamp:
![image](https://user-images.githubusercontent.com/2954254/183778849-b9960c86-7e7b-4c55-bc51-704f7869aedf.png)

2022-08-10 18:51 UTC, facontidavide commented on plotjuggler_plugins/DataLoadCSV/dataload_csv.cpp
> +                         .arg(column_names.size()).arg(linecount+2).arg(t_str));
Am I wrong or you have 5 arg() here and only 3 are required?

2022-08-10 22:18 UTC, facontidavide requested changes

2022-08-10 22:18 UTC, facontidavide commented on plotjuggler_plugins/DataLoadCSV/dataload_csv.cpp
> +                         .arg(column_names.size()).arg(linecount+2).arg(t_str));
```suggestion
                         .arg(column_names.size());
```

2022-08-11 04:55 UTC, Bartimaeus- commented
Missing a parenthesis from that last tweak, I will fix tomorrow

2022-08-12 03:08 UTC, merged

2022-08-12 03:22 UTC, facontidavide commented
Thanks a lot