#879 Inverted option for STEPS style
facontidavide/PlotJuggler pull request #880
Opened 2023-11-02 00:19 UTC by zdavkeos

New line style like STEPS but drawn the opposite way.
<img width="866" alt="Screenshot 2023-11-01 at 7 16 40 PM" src="https://github.com/facontidavide/PlotJuggler/assets/172684/c09f54a1-3e75-4bdf-978c-44bcf737b899">

2023-11-18 20:38 UTC, zdavkeos commented
@facontidavide & @mikkelti I am not crazy about the name "Inverted Steps", that's qwt's terminology. I would be very open to any suggestions.

2023-11-22 11:13 UTC, mikkelti commented
@zdavkeos Inspired by matplotlib's terminology, you could call them `Steps (pre)` and `Steps (post)` or something like that.

2023-12-14 11:54 UTC, facontidavide requested changes

2023-12-14 11:54 UTC, facontidavide commented on plotjuggler_app/plotwidget_editor.ui
> +               <string>Inverted (post)</string>
```suggestion
               <string>Step (post)</string>
```

2023-12-14 20:28 UTC, zdavkeos commented
Good catch @facontidavide , Thanks!

2024-01-09 10:53 UTC, merged